### ISSUE TITLE
Configuration for Tailwind v3.0

### ISSUE THREAD

**Issue by geraldioeres** [ovisannn/disspace-UI#1]
https://github.com/ovisannn/disspace-UI/blob/70cfb646d97468e05fd88d7ced51e4451aec5ddf/tailwind.config.js#L2-L6
Kalau dari docs yang ini katanya nggak perlu lagi pakai "mode" & "purge" di tailwind.config.js nya.

[https://tailwindcss.com/docs/upgrade-guide#configure-content-sources](url)

**Comment by ovisannn** [comment]
> https://github.com/ovisannn/disspace-UI/blob/70cfb646d97468e05fd88d7ced51e4451aec5ddf/tailwind.config.js#L2-L6
> 
> 
> Kalau dari docs yang ini katanya nggak perlu lagi pakai "mode" & "purge" di tailwind.config.js nya.
> [https://tailwindcss.com/docs/upgrade-guide#configure-content-sources](url)

oke berarti nanti di file tailwind.config.js langsung comment atau hapus aja mode jit sama purge nya ya. terlanjur buat branch soalnya takutnya conflict wkwk
